# Generated by Django 3.1.3 on 2020-11-27 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_autor', models.CharField(max_length=40, verbose_name='Autor')),
                ('titulo_msg', models.CharField(max_length=50, verbose_name='Título da mensagem')),
                ('texto_msg', models.TextField(max_length=500, verbose_name='Mensagem')),
                ('data_pub', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da publicação')),
                ('url_foto', models.URLField(blank=True, null=True, verbose_name='URL foto Google Drive')),
            ],
        ),
    ]
