# Generated by Django 3.1.3 on 2020-11-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagens',
            name='url_foto',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='URL foto Google Drive (Opcional)'),
        ),
    ]
