# Generated by Django 3.1.3 on 2020-11-27 15:15

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensagens', '0003_auto_20201127_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagens',
            name='usuario',
            field=models.ForeignKey(blank=True, default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
