# Generated by Django 3.1.3 on 2021-01-27 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0005_auto_20201127_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagens',
            options={'ordering': ['-id']},
        ),
    ]
